import { AppImages } from "../assets/images";

export interface user {
  id: string;
  name: string;
  age: number;
  gender: string;
  profile_pic_url: any;
  bio: string;
  interests: string[];
  location_latitude: number;
  location_longitude: number;
  education: string[];
  work: string[];
  languages: string[];
  lifestyle_preferences: string[];
  smoking: string;
  drinking: string;
  pets: string;
  relationship: string;
  religion: string;
  budget: number;
  preferred_age_min: number;
  preferred_age_max: number;
  preferred_gender: string[];
  preferred_location_range: number;
}

export type userWithaddress = {
  address: string;
} & user;

export const data = [
  {
    id: "cliruj7nb000h08ladvybf8m8",
    name: "Emily Johnson",
    age: 32,
    gender: "female",
    profile_pic_url: AppImages.person_1,
    bio: "I'm a passionate artist who loves painting and exploring new art galleries. Looking for someone who shares my love for creativity and adventure!",
    interests: ["painting", "art galleries", "reading", "traveling"],
    location_latitude: 26.16901,
    location_longitude: 91.780143,
    education: ["5f849c4cf55b4d48342872e5", "5f849c4cf55b4d48342872e6"],
    work: ["5f849c4cf55b4d48342872e7"],
    languages: ["English", "French"],
    lifestyle_preferences: ["Cleanliness", "Quietness", "Outdoor Activities"],
    smoking: "never",
    drinking: "socially",
    pets: "Cats allowed",
    relationship: "single",
    religion: "atheist",
    budget: 1500,
    preferred_age_min: 28,
    preferred_age_max: 40,
    preferred_gender: ["male", "female", "non-binary"],
    preferred_location_range: 10,
  },
  {
    id: "cliruf5hr000108la6q3m0rym",
    name: "Michael Anderson",
    age: 45,
    gender: "male",
    profile_pic_url: AppImages.person_2,
    bio: "I'm a nature enthusiast and outdoor lover. Hiking and camping are my favorite weekend activities. Hoping to find a partner who appreciates the beauty of the great outdoors!",
    interests: ["hiking", "camping", "photography", "gardening"],
    location_latitude: 34.0522,
    location_longitude: -118.2437,
    education: ["5f849c4cf55b4d48342872e8", "5f849c4cf55b4d48342872e9"],
    work: ["5f849c4cf55b4d48342872ea"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: ["Outdoor Activities", "Socializing", "Fitness"],
    smoking: "never",
    drinking: "socially",
    pets: "Dogs allowed",
    relationship: "single",
    religion: "spiritual",
    budget: 2500,
    preferred_age_min: 30,
    preferred_age_max: 50,
    preferred_gender: ["female"],
    preferred_location_range: 20,
  },
  {
    id: "cliruflgh000308la5oq09152",
    name: "Sophia Lee",
    age: 29,
    gender: "female",
    profile_pic_url: AppImages.person_3,
    bio: "I'm a software developer with a passion for coding and technology. Looking for someone who shares my love for programming and enjoys intellectual conversations!",
    interests: ["programming", "technology", "video games", "reading"],
    location_latitude: 37.7749,
    location_longitude: -122.4194,
    education: ["5f849c4cf55b4d48342872eb"],
    work: ["5f849c4cf55b4d48342872ec", "5f849c4cf55b4d48342872ed"],
    languages: ["English", "Japanese"],
    lifestyle_preferences: ["Cleanliness", "Quietness", "Fitness"],
    smoking: "never",
    drinking: "socially",
    pets: "No pets",
    relationship: "single",
    religion: "agnostic",
    budget: 2000,
    preferred_age_min: 25,
    preferred_age_max: 35,
    preferred_gender: ["male"],
    preferred_location_range: 15,
  },
  {
    id: "clirufsz1000408la85w87p0o",
    name: "Oliver Davis",
    age: 38,
    gender: "male",
    profile_pic_url: AppImages.person_4,
    bio: "I'm a fitness enthusiast and personal trainer. I love helping people achieve their fitness goals and staying active. Looking for a partner who values a healthy lifestyle!",
    interests: ["fitness", "nutrition", "traveling", "cooking"],
    location_latitude: 51.5074,
    location_longitude: -0.1278,
    education: ["5f849c4cf55b4d48342872ee", "5f849c4cf55b4d48342872ef"],
    work: ["5f849c4cf55b4d48342872f0"],
    languages: ["English", "German"],
    lifestyle_preferences: ["Fitness", "Outdoor Activities"],
    smoking: "never",
    drinking: "socially",
    pets: "Dogs allowed",
    relationship: "single",
    religion: "atheist",
    budget: 3000,
    preferred_age_min: 30,
    preferred_age_max: 45,
    preferred_gender: ["female"],
    preferred_location_range: 10,
  },
  {
    id: "clirug38j000508la3eracj6x",
    name: "Ava Wilson",
    age: 27,
    gender: "female",
    profile_pic_url: AppImages.person_5,
    bio: "I'm a travel blogger and adventurer. Exploring new destinations and experiencing different cultures is my passion. Seeking a companion to share exciting travel experiences with!",
    interests: ["traveling", "photography", "writing", "hiking"],
    location_latitude: 48.8566,
    location_longitude: 2.3522,
    education: ["5f849c4cf55b4d48342872f1"],
    work: ["5f849c4cf55b4d48342872f2"],
    languages: ["English", "French", "Spanish"],
    lifestyle_preferences: [
      "Cleanliness",
      "Quietness",
      "Outdoor Activities",
      "Socializing",
    ],
    smoking: "never",
    drinking: "socially",
    pets: "No pets",
    relationship: "single",
    religion: "spiritual",
    budget: 2500,
    preferred_age_min: 25,
    preferred_age_max: 35,
    preferred_gender: ["male", "female"],
    preferred_location_range: 20,
  },
  {
    id: "clirugb2p000608la3vys8pcl",
    name: "William Thompson",
    age: 31,
    gender: "male",
    profile_pic_url: AppImages.person_6,
    bio: "I'm an avid reader and book lover. I enjoy spending my weekends immersed in a good novel or exploring quaint bookstores. Seeking a fellow bookworm to share literary discussions and cozy reading sessions!",
    interests: ["reading", "writing", "coffee", "music"],
    location_latitude: 40.7128,
    location_longitude: -74.006,
    education: ["5f849c4cf55b4d48342872f3", "5f849c4cf55b4d48342872f4"],
    work: ["5f849c4cf55b4d48342872f5"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: ["Quietness", "Socializing"],
    smoking: "never",
    drinking: "socially",
    pets: "Cats allowed",
    relationship: "single",
    religion: "agnostic",
    budget: 1000,
    preferred_age_min: 25,
    preferred_age_max: 35,
    preferred_gender: ["female"],
    preferred_location_range: 15,
  },
  {
    id: "clirugihx000708lahel75pku",
    name: "Charlotte Rodriguez",
    age: 29,
    gender: "female",
    profile_pic_url: AppImages.person_7,
    bio: "I'm a nature lover and environmental activist. Protecting the planet is important to me, and I enjoy hiking, gardening, and sustainable living. Looking for a like-minded partner to make a positive impact together!",
    interests: ["hiking", "gardening", "sustainability", "yoga"],
    location_latitude: 34.0522,
    location_longitude: -118.2437,
    education: ["5f849c4cf55b4d48342872f6"],
    work: ["5f849c4cf55b4d48342872f7", "5f849c4cf55b4d48342872f8"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: [
      "Cleanliness",
      "Quietness",
      "Outdoor Activities",
      "Fitness",
    ],
    smoking: "never",
    drinking: "socially",
    pets: "Dogs allowed",
    relationship: "single",
    religion: "spiritual",
    budget: 2000,
    preferred_age_min: 28,
    preferred_age_max: 40,
    preferred_gender: ["male"],
    preferred_location_range: 20,
  },
  {
    id: "clirugq1w000808la8bod50og",
    name: "Charlotte Rodriguez",
    age: 29,
    gender: "female",
    profile_pic_url: AppImages.person_8,
    bio: "I'm a nature lover and environmental activist. Protecting the planet is important to me, and I enjoy hiking, gardening, and sustainable living. Looking for a like-minded partner to make a positive impact together!",
    interests: ["hiking", "gardening", "sustainability", "yoga"],
    location_latitude: 34.0522,
    location_longitude: -118.2437,
    education: ["5f849c4cf55b4d48342872f6"],
    work: ["5f849c4cf55b4d48342872f7", "5f849c4cf55b4d48342872f8"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: [
      "Cleanliness",
      "Quietness",
      "Outdoor Activities",
      "Fitness",
    ],
    smoking: "never",
    drinking: "socially",
    pets: "Dogs allowed",
    relationship: "single",
    religion: "spiritual",
    budget: 2000,
    preferred_age_min: 28,
    preferred_age_max: 40,
    preferred_gender: ["male"],
    preferred_location_range: 20,
  },
  {
    id: "clirugyh4000908labub8eaon",
    name: "James Wilson",
    age: 35,
    gender: "male",
    profile_pic_url: AppImages.person_9,
    bio: "I'm a food enthusiast and home chef. Cooking is my passion, and I love experimenting with different flavors and cuisines. Seeking a partner who appreciates good food and culinary adventures!",
    interests: ["cooking", "food tasting", "traveling", "music"],
    location_latitude: 37.7749,
    location_longitude: -122.4194,
    education: ["5f849c4cf55b4d48342872f9", "5f849c4cf55b4d48342872fa"],
    work: ["5f849c4cf55b4d48342872fb"],
    languages: ["English", "Italian"],
    lifestyle_preferences: ["Cleanliness", "Socializing"],
    smoking: "never",
    drinking: "socially",
    pets: "No pets",
    relationship: "single",
    religion: "agnostic",
    budget: 3000,
    preferred_age_min: 30,
    preferred_age_max: 45,
    preferred_gender: ["female"],
    preferred_location_range: 10,
  },
  {
    id: "cliruh95g000a08la7m8d62hu",
    name: "Sophie Clark",
    age: 28,
    gender: "female",
    profile_pic_url: AppImages.person_10,
    bio: "I'm a software engineer with a love for technology and problem-solving. In my free time, I enjoy playing video games and attending tech conferences. Seeking someone who shares my passion for coding and geeky interests!",
    interests: ["programming", "video games", "tech conferences", "traveling"],
    location_latitude: 51.5074,
    location_longitude: -0.1278,
    education: ["5f849c4cf55b4d48342872fc"],
    work: ["5f849c4cf55b4d48342872fd"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: ["Cleanliness", "Quietness", "Fitness"],
    smoking: "never",
    drinking: "socially",
    pets: "No pets",
    relationship: "single",
    religion: "atheist",
    budget: 2000,
    preferred_age_min: 25,
    preferred_age_max: 35,
    preferred_gender: ["male", "female"],
    preferred_location_range: 10,
  },
  {
    id: "cliruhgsp000b08lagfjp0asi",
    name: "Ethan Moore",
    age: 33,
    gender: "male",
    profile_pic_url: AppImages.person_5,
    bio: "I'm an adventure seeker and adrenaline junkie. Skydiving and bungee jumping are my favorite activities. Looking for a thrill-loving partner to join me on exciting escapades!",
    interests: ["adventure sports", "traveling", "photography", "music"],
    location_latitude: 48.8566,
    location_longitude: 2.3522,
    education: ["5f849c4cf55b4d48342872fe"],
    work: ["5f849c4cf55b4d48342872ff"],
    languages: ["English", "French"],
    lifestyle_preferences: ["Outdoor Activities", "Socializing"],
    smoking: "never",
    drinking: "socially",
    pets: "No pets",
    relationship: "single",
    religion: "agnostic",
    budget: 2500,
    preferred_age_min: 28,
    preferred_age_max: 40,
    preferred_gender: ["female"],
    preferred_location_range: 20,
  },
  {
    id: "cliruhl6z000c08lahe7g4o3f",
    name: "Isabella Turner",
    age: 30,
    gender: "female",
    profile_pic_url: AppImages.person_1,
    bio: "I'm a nature lover and wildlife enthusiast. Exploring national parks and wildlife sanctuaries is my idea of a perfect getaway. Seeking a partner who shares my love for the great outdoors!",
    interests: [
      "hiking",
      "wildlife photography",
      "nature conservation",
      "reading",
    ],
    location_latitude: 37.7749,
    location_longitude: -122.4194,
    education: ["5f849c4cf55b4d4834287300"],
    work: ["5f849c4cf55b4d4834287301"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: [
      "Cleanliness",
      "Quietness",
      "Outdoor Activities",
      "Fitness",
    ],
    smoking: "never",
    drinking: "socially",
    pets: "Dogs allowed",
    relationship: "single",
    religion: "spiritual",
    budget: 2000,
    preferred_age_min: 28,
    preferred_age_max: 40,
    preferred_gender: ["male"],
    preferred_location_range: 15,
  },
  {
    id: "cliruhl6z000c08hahe7g4o3f",
    name: "Liam Baker",
    age: 25,
    gender: "male",
    profile_pic_url: AppImages.person_4,
    bio: "I'm a musician and music producer. I spend most of my time writing and composing music. Looking for someone who appreciates music and shares a love for creativity!",
    interests: ["music", "songwriting", "playing instruments", "concerts"],
    location_latitude: 34.0522,
    location_longitude: -118.2437,
    education: ["5f849c4cf55b4d4834287302", "5f849c4cf55b4d4834287303"],
    work: ["5f849c4cf55b4d4834287304"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: ["Quietness", "Socializing"],
    smoking: "never",
    drinking: "socially",
    pets: "No pets",
    relationship: "single",
    religion: "agnostic",
    budget: 1500,
    preferred_age_min: 20,
    preferred_age_max: 30,
    preferred_gender: ["female"],
    preferred_location_range: 10,
  },
  {
    id: "clirui1b0000e08la3ao7dn1n",
    name: "Emma Harris",
    age: 29,
    gender: "female",
    profile_pic_url: AppImages.person_7,
    bio: "I'm a travel enthusiast and foodie. Exploring new cuisines and trying out local delicacies is my passion. Seeking a travel companion with an adventurous palate!",
    interests: ["traveling", "food tasting", "photography", "hiking"],
    location_latitude: 40.7128,
    location_longitude: -74.006,
    education: ["5f849c4cf55b4d4834287305"],
    work: ["5f849c4cf55b4d4834287306"],
    languages: ["English", "French", "Italian"],
    lifestyle_preferences: ["Cleanliness", "Outdoor Activities", "Socializing"],
    smoking: "never",
    drinking: "socially",
    pets: "No pets",
    relationship: "single",
    religion: "spiritual",
    budget: 3000,
    preferred_age_min: 25,
    preferred_age_max: 35,
    preferred_gender: ["male", "female"],
    preferred_location_range: 20,
  },
  {
    id: "clirui7me000f08labv1y8u4p",
    name: "Noah Turner",
    age: 32,
    gender: "male",
    profile_pic_url: AppImages.person_8,
    bio: "I'm a nature lover and outdoor enthusiast. Hiking, camping, and stargazing are some of my favorite activities. Seeking a partner who shares my love for the natural world!",
    interests: ["hiking", "camping", "photography", "astronomy"],
    location_latitude: 51.5074,
    location_longitude: -0.1278,
    education: ["5f849c4cf55b4d4834287307"],
    work: ["5f849c4cf55b4d4834287308"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: [
      "Cleanliness",
      "Quietness",
      "Outdoor Activities",
      "Fitness",
    ],
    smoking: "never",
    drinking: "socially",
    pets: "Dogs allowed",
    relationship: "single",
    religion: "agnostic",
    budget: 2000,
    preferred_age_min: 28,
    preferred_age_max: 40,
    preferred_gender: ["female"],
    preferred_location_range: 15,
  },
  {
    id: "cliruiee2000g08la1cn3frxn",
    name: "John Smith",
    age: 28,
    gender: "male",
    profile_pic_url: AppImages.person_3,
    bio: "I'm a software engineer who loves hiking and playing the guitar. Looking to meet new people and explore new adventures!",
    interests: ["hiking", "guitar", "technology", "traveling"],
    location_latitude: 37.7749,
    location_longitude: -122.4194,
    education: ["5f849c4cf55b4d48342872e2", "5f849c4cf55b4d48342872e3"],
    work: ["5f849c4cf55b4d48342872e4"],
    languages: ["English", "Spanish"],
    lifestyle_preferences: ["Cleanliness", "Quietness", "Outdoor Activities"],
    smoking: "never",
    drinking: "socially",
    pets: "Dogs allowed",
    relationship: "single",
    religion: "agnostic",
    budget: 2000,
    preferred_age_min: 25,
    preferred_age_max: 35,
    preferred_gender: ["female"],
    preferred_location_range: 10,
  },
];

export async function fetchUsers(page: number = 1, pageSize: number = 10) {
  return new Promise<userWithaddress[]>(async (resolve, reject) => {
    const startIndex = (page - 1) * pageSize;
    const endIndex = startIndex + pageSize;

    if (startIndex < data.length && endIndex < data.length + 1) {
      const paginatedData = data.slice(startIndex, endIndex);

      const users: userWithaddress[] = [];

      for (let i = 0; i < paginatedData.length; i++) {
        // const response = await fetch(
        //   `https://nominatim.openstreetmap.org/reverse?format=json&lat=${paginatedData[i].location_latitude}&lon=${paginatedData[i].location_longitude}`
        // );
        // const data = await response.json();
        users.push({
          ...paginatedData[i],
          address: `${"Guwahati"}, ${"AS"}`,
        });
      }

      resolve(users);
    } else {
      reject("no more data");
    }
  });
}

export async function fetchUserByID(id: string) {
  return new Promise<user>((resolve, reject) => {
    setTimeout(() => {
      const user = data.filter((user) => user.id === id);

      resolve(user[0]);
    }, 100);
  });
}
